### ISSUE TITLE
[Feature] Spelling algebra conditions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#138]
```
example:

algebra:
 - xlit/xxx/yyy/
 - (foo=no&bar=yes)xform/xxx/yyy/
 - (pred)derive/xxx/yyy/

algebra_options:
  foo: yes
  bar: no
  num: 3
  pred: ((!foo|bar)&num=3)
```

Original issue reported on code.google.com by `chen....@gmail.com` on 7 May 2012 at 3:39
