### ISSUE TITLE
编译输入方案时同时编译所依赖的方案（五筆・拼音）

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#197]
```
RT！我选了五笔.拼音，可是只能打五笔编码呀，打拼音还要��
�入什么前缀吗？
```

Original issue reported on code.google.com by `lianyi1...@gmail.com` on 23 Jul 2012 at 11:57

**Comment by GoogleCodeExporter** [comment]
```
需要启用输入方案【袖珍简化字拼音】。
```

Original comment by `chen....@gmail.com` on 23 Jul 2012 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
谢谢，可以了。
顺便问下特殊符号如何输入呢？
```

Original comment by `lianyi1...@gmail.com` on 23 Jul 2012 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
TODO 编译输入方案时同时编译所依赖的方案

AL 2: 特殊符号用 z 开头的那些编码
```

Original comment by `chen....@gmail.com` on 23 Jul 2012 at 12:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `chen....@gmail.com` on 23 Jul 2012 at 12:55
- Changed title: **五笔拼音混输要怎样实现？——编译输入方案时同时编译所依赖的方案**
- Changed state: **Accepted**
- Added labels: **Type-Enhancement**, **OpSys-All**, **Component-Scripts**, **Project-Rimexx**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
我也来说一句。

五笔拼音混输模式可以调出Z开头的特殊符号的。。。
```

Original comment by `lelyseas...@gmail.com` on 24 Jul 2012 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
列入開發計劃
```

Original comment by `chen....@gmail.com` on 15 Aug 2012 at 2:17
- Changed title: **编译输入方案时同时编译所依赖的方案**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
需要启用输入方案【袖珍简化字拼音]。这一句没有看明白，�
��有简写的代码吗？
patch:
  schema_list:
    - schema: luna_pinyin   # 朙月拼音
    - schema: terra_pinyin  # 地球拼音 dì qiú pīn yīn
    - schema: bopomofo      # 注音
    - schema: jyutping      # 粵拼
    - schema: cangjie5      # 倉頡五代
    - schema: quick5        # 速成
    - schema: wubi86        # 五笔86
    - schema: wubi_pinyin   # 五笔拼音混合輸入
    - schema: double_pinyin        # 自然碼雙拼
    - schema: double_pinyin_mspy   # 微軟雙拼
    - schema: double_pinyin_abc    # 智能ABC雙拼
    - schema: double_pinyin_flypy  # 小鶴雙拼
    - schema: wugniu        # 吳語上海話（新派）
    - schema: wugniu_lopha  # 吳語上海話（老派）
    - schema: triungkox3p   # 中古漢語三拼
    - schema: zyenpheng     # 中古漢語全拼
    - schema: ipa_xsampa    # X-SAMPA 國際音標

没有发现！ :(
```

Original comment by `xiaokang.zh@gmail.com` on 15 Aug 2012 at 3:45
