### ISSUE TITLE
注音模式無法字母選字

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#278]
```
首先標準注音裏陰平聲不是不打，而是空格鍵。
其次在小狼毫輸入了注音和聲調後想選字時，會直接開始打��
�一個字的注音，而不是確認一個字。
修改建議：在新酷音裏是打完一串完整帶聲調的注音後空格��
�屏，再選字。不然就只好用上下鍵來選字了……

請提供以下信息，幫我們定位問題。

1. 輸入法的款式：（請選擇）小狼毫
   輸入法版本號：（請填寫）09151

2. 操作系統類型：（請選擇）Windows
   操作系統版本：（請填寫）XP SP3

3. 輸入方案名稱：（如果問題涉及交互方式、輸入效果等
，請填寫）注音

問題發現的歷程：
注音比全拼重碼少。但大千鍵位痛苦，我用的是倚天。另外��
�個問題是鍵長不固定，不夠完美。
我想改成雙拼+dfjkl聲調+空格上屏+asdfghjkl選字，這樣鍵長適中
，還解放了數字鍵，純 26 
字母打字（這絕對是嘗試過形碼的注音用戶看到雙拼後一定��
�想到的方案）。還可以 asdfghjklqwertyuiopzxcvbnm 
選字，候選項目 26 個，再也不用翻頁了哦也（好變態）。
結果用 bopomofo.schema.yaml 
改了半天，不知道為什麼，總是會變成普通的雙拼。文檔裏��
�能abc雙拼的修改解釋沒有涉及地球拼音部分，玩不轉。然後�
��出注音來看了一下，發現和新酷音不大一樣。

附我的失敗嘗試：
# Rime schema
# vim: set sw=2 sts=2 et:
# encoding: utf-8

schema:
  schema_id: fly
  name: 小鶴三拼
  version: "0.1"
  author:
    - 
  description: |
    帶聲調的雙拼。小鶴雙拼，聲調爲dfjkl，選字用asdfghjkl;

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: simplification
    states: [ 漢字, 汉字 ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - r10n_translator
    - reverse_lookup_translator
  filters:
    - simplifier
    - uniquifier

menu:
  alternative_select_keys: "ASDFGHJKLQWERTYUIOPZXCVBNM"

speller:
  alphabet: 'zyxwvutsrqponmlkjihgfedcba'
  delimiter: " '"
  algebra:
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Q/
    - xform/(.)ei$/$1W/
    - xform/uan$/R/
    - xform/[uv]e$/T/
    - xform/un$/Y/
    - xform/^sh/U/
    - xform/^ch/I/
    - xform/^zh/V/
    - xform/uo$/O/
    - xform/ie$/P/
    - xform/i?ong$/S/
    - xform/ing$|uai$/K/
    - xform/(.)ai$/$1D/
    - xform/(.)en$/$1F/
    - xform/(.)eng$/$1G/
    - xform/[iu]ang$/L/
    - xform/(.)ang$/$1H/
    - xform/ian$/M/
    - xform/(.)an$/$1J/
    - xform/(.)ou$/$1Z/
    - xform/[iu]a$/X/
    - xform/iao$/N/
    - xform/(.)ao$/$1C/
    - xform/ui$/V/
    - xform/in$/B/
    - 'xlit|QWRTYUIOPSDFGHJKLZXCVBNM12345|qwrtyuiopsdfghjklzxcvbnmdfjkl|'

translator:
  dictionary: terra_pinyin
  prism: fly
  preedit_format:


reverse_lookup:
  dictionary: cangjie5
  enable_completion: true
  prefix: "`"
  tips: 〔倉頡〕
  preedit_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
  comment_format:

punctuator:
  import_preset: default

key_binder:
  import_preset: default

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*$"
```

Original issue reported on code.google.com by `ForesterLian` on 5 Oct 2012 at 12:28
- Merged into: #27
