### ISSUE TITLE
fcitx-rime里边切换中文和英文，怎么把输入了的字母都显示出来。

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#364]
```
請寫下能夠重現此狀況的操作步驟：
1.
# ~/.config/fcitx/config
[Hotkey]
SwitchKey=R_SHIFT
[Output]
# Commit when toggle state
# Available Value:
# True False
SendTextWhenSwitchEng=True
#这样在一般的fcitx输入里边，按shift之后，输入的文字都是直
接显示字母。
2.切换成fcitx-rime，输入若干字母然后按下shift。
3.

所得的結果是這個樣：屏幕上什么都没有
預期結果該是那個樣：打出若干字母

請提供以下信息，幫我們定位問題。

1. 輸入法的款式：（請選擇）fcitx-rime
   輸入法版本號：（請填寫）0.2.0

2. 操作系統類型：（請選擇）Linux
   操作系統版本：（請填寫）3.6.11

3. 輸入方案名稱：（如果問題涉及交互方式、輸入效果等
，請填寫）luna_pinyin.schema.yaml 

還想再說幾句：

输入若干字母之后按.翻页，再输入若干字母，就会把.也显出
，而且没有候选项。@csslayer说这是rime的问题。
https://github.com/fcitx/fcitx-rime/issues/6


```

Original issue reported on code.google.com by `tus...@gmail.com` on 2 Feb 2013 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
试着取消了fcitx的切换键，结果是shift根本没反映。
● dog ~/.config/fcitx/rime/default.yaml 
ascii_composer:
  switch_key:
    Control_L: noop
    Control_R: noop
    Shift_L: inline_ascii
    Shift_R: commit_text
#(以下省略若干)
#这几行，不知道是做什么的。好像有点关系。
```

Original comment by `tus...@gmail.com` on 2 Feb 2013 at 12:29

**Comment by GoogleCodeExporter** [comment]
```
請參考gist文中註釋，設定 Rime 的模式切換鍵（與 fcitx 
配置無關）：

https://gist.github.com/lotem/2981316
```

Original comment by `chen....@gmail.com` on 5 Feb 2013 at 9:02
- Changed state: **Done**
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
patch:
  schema_list: 
    - schema: luna_pinyin
  ascii_composer/switch_key:
    Shift_R: commit_code

设定后无效。试着取消了fcitx的切换键，结果是shift根本没反�
��。
```

Original comment by `tus...@gmail.com` on 5 Feb 2013 at 2:43
