### ISSUE TITLE
希望能够设置默认英文输入状态

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#458]
```
請寫下能夠重現此狀況的操作步驟：
1.现在所有版本默认中文输入

所得的結果是這個樣：希望能设置所有程序默认英文输入
預期結果該是那個樣：目前好像只能针对单个程序设定输入��
�态

請提供以下信息，幫我們定位問題。

1. 輸入法的款式：（請選擇）小狼毫
   輸入法版本號：（請填寫）所有版本

2. 操作系統類型：（請選擇）Windows
   操作系統版本：（請填寫）Win7

還想再說幾句：因为电脑上只有这一个输入法，所以不需要��
�换输入法，但默认中文输入就经常需要按Shift切换，因此很��
�方便，希望可以设置默认英文输入



```

Original issue reported on code.google.com by `xuedeng...@gmail.com` on 31 Jul 2013 at 3:50

**Comment by GoogleCodeExporter** [comment]
```
# luna_pinyin.custom.yaml

patch:
  switches:
    - name: ascii_mode
      reset: 1                # reset 的作用是當從其他輸入方案切換到本方案時，
      states: [ 中文, 西文 ]  # 重設爲指定的狀態，而不保留在前一個方案中設定的狀態。
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification
      states: [ 漢字, 汉字 ]
```

Original comment by `chen....@gmail.com` on 31 Jul 2013 at 5:09
- Changed state: **Done**
- Removed labels: **Type-Defect**, **Priority-Medium**
