### ISSUE TITLE
匹配特定的輸入串，進入臨時西文模式

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#47]
```
如默認配置爲：

＊大寫字母開頭的輸入串
＊數字開頭的輸入串
＊http: ftp: www. xxx@ 等包含特徵字符的格式


```

Original issue reported on code.google.com by `chen....@gmail.com` on 25 Dec 2011 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
配置方法提要

processors:
  - recognizer
segmentors:
  - matcher

recognizer:
  patterns:
    url: "regex pattern"
    number: "regex..."

```

Original comment by `chen....@gmail.com` on 1 Jan 2012 at 11:43
- Changed state: **Fixed**
