### ISSUE TITLE
如何使用固態詞典引用多份碼表文件以實現分類詞庫

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lotem/rimeime#490]
```
請寫下能夠重現此狀況的操作步驟：
1.如何引用多份码表?比如想同时使用emoji和pinyin_simp,应该如何
设置. 
2.
3.


1. 輸入法的款式：鼠鬚管 
   輸入法版本號：0.9.21

2. 操作系統類型：mac
   操作系統版本：10.9 gm

3. 輸入方案名稱：wubi86




```

Original issue reported on code.google.com by `zhixun.lin@gmail.com` on 7 Oct 2013 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
不同編碼不宜合併到一部詞典中。
emoji 看似是用拼音編碼的，但其實不同：
"biaoqing" 並非拼音音節編碼 "biao qing"，如果導入到 pinyin_simp 
將影響拼音的音節切分。
分類詞庫則不然，因爲分類詞庫也是用拼音音節編碼的，只��
�增加了一些詞條。
以下代碼用反查的方法實現 /biaoqing 輸入表情。

# pinyin_simp.custom.yaml
# encoding: utf-8

patch:
  schema/dependencies:
    - stroke_simp
    - emoji
  engine/translators:
    - punct_translator
    - script_translator
    - reverse_lookup_translator
    - reverse_lookup_translator@emoji
  emoji:
    dictionary: emoji
    enable_completion: true
    prefix: '/'
    tips: 〔表情〕
  recognizer/patterns/reverse_lookup: '/[a-z]+$'

```

Original comment by `contral...@gmail.com` on 8 Oct 2013 at 5:28
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**
